version: '2.3'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432